# Generated by Django 3.2.7 on 2022-01-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h_finance', '0005_auto_20220110_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inkome',
            options={'ordering': ['-data']},
        ),
        migrations.RenameField(
            model_name='inkome',
            old_name='data_i',
            new_name='data',
        ),
    ]
