# Generated by Django 3.2.7 on 2022-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_finance', '0006_auto_20220111_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inkome',
            name='data',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
