# Generated by Django 3.2.7 on 2022-01-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h_finance', '0007_alter_inkome_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inkome',
        ),
    ]
